insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (1, 6, 'Geological Engineer', 'Frankie Marris', '€32559,28');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (2, 6, 'Developer I', 'Sibilla Fredy', '€27188,83');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (3, 3, 'Geological Engineer', 'Cullin Atwell', '€31180,18');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (4, 8, 'Budget/Accounting Analyst I', 'Reeta Ticksall', '€34437,69');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (5, 9, 'General Manager', 'Lorens Poulsen', '€22519,54');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (6, 9, 'Junior Executive', 'Paige Scranney', '€31736,21');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (7, 8, 'Help Desk Operator', 'Rob Slark', '€27291,83');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (8, 10, 'Senior Editor', 'Willyt Berisford', '€31433,85');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (9, 5, 'Staff Scientist', 'Gabriel Mogford', '€23125,06');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (10, 3, 'Community Outreach Specialist', 'Creigh Rathborne', '€33284,01');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (11, 6, 'Senior Sales Associate', 'Andrew Wellbank', '€34306,69');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (12, 8, 'Recruiting Manager', 'Thayne Dunbobin', '€25127,69');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (13, 4, 'Senior Quality Engineer', 'Eliot Crippill', '€25719,20');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (14, 5, 'Senior Sales Associate', 'Meredithe Boon', '€32281,59');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (15, 10, 'Sales Associate', 'Jerrylee Farlow', '€32171,50');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (16, 1, 'VP Product Management', 'Rae Prazor', '€34829,65');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (17, 8, 'Occupational Therapist', 'Lian Berre', '€24693,06');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (18, 5, 'Help Desk Operator', 'Gabie Vowden', '€33190,99');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (19, 1, 'Registered Nurse', 'Eda Widger', '€23365,87');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (20, 3, 'Operator', 'Neile Bartrum', '€35985,31');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (21, 4, 'Research Assistant III', 'Ayn Ortmann', '€24909,11');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (22, 7, 'Computer Systems Analyst IV', 'Brandea Uwins', '€32104,73');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (23, 5, 'Help Desk Operator', 'Hyacinthie Bellhouse', '€29983,84');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (24, 6, 'Senior Quality Engineer', 'Sarene Sexty', '€29148,28');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (25, 7, 'Director of Sales', 'Keefer Swanson', '€34276,74');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (26, 8, 'Structural Engineer', 'Thacher Annies', '€29524,97');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (27, 3, 'Geologist I', 'Kary Gurry', '€28544,24');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (28, 7, 'Structural Analysis Engineer', 'Aloysia Peddersen', '€32586,82');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (29, 6, 'Electrical Engineer', 'Nikolai Giottoi', '€23543,11');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (30, 3, 'Staff Scientist', 'Anni Dike', '€23950,87');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (31, 3, 'Senior Cost Accountant', 'Corrine Barsam', '€25036,45');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (32, 6, 'Sales Representative', 'Seka Sandaver', '€33898,93');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (33, 4, 'Executive Secretary', 'Leo Molines', '€32462,63');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (34, 8, 'Programmer II', 'Leicester Ewbanck', '€31287,38');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (35, 3, 'Cost Accountant', 'Shell Torrecilla', '€27998,90');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (36, 1, 'Account Executive', 'Herby Gerrens', '€25243,00');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (37, 4, 'Recruiter', 'Adena Rutland', '€34006,25');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (38, 3, 'Administrative Assistant I', 'Pammie Kiddle', '€22278,79');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (39, 1, 'Analyst Programmer', 'Marsha Kobus', '€32057,74');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (40, 3, 'Web Designer III', 'Alvie Philipson', '€35847,88');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (41, 9, 'Web Developer III', 'Lesley Wethered', '€27309,60');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (42, 8, 'Research Associate', 'Tammie Le Claire', '€22531,56');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (43, 10, 'Cost Accountant', 'Koo Joder', '€25336,52');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (44, 7, 'Recruiter', 'Sophia Downton', '€27061,58');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (45, 1, 'Quality Control Specialist', 'Barbaraanne de Savery', '€22119,98');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (46, 2, 'Internal Auditor', 'Fletch Shepheard', '€33341,80');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (47, 1, 'Research Associate', 'Coop Goforth', '€31841,10');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (48, 6, 'Engineer I', 'Rosco Kinmond', '€23240,91');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (49, 3, 'Product Engineer', 'Benton Baynham', '€33175,11');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (50, 10, 'Internal Auditor', 'Diana Fiddiman', '€33548,77');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (51, 5, 'Editor', 'Rosa Standring', '€28902,40');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (52, 1, 'Technical Writer', 'Conny Kaminski', '€22373,69');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (53, 4, 'Geologist II', 'Edin Baszkiewicz', '€25781,07');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (54, 3, 'Biostatistician I', 'Chev Tribe', '€26718,67');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (55, 1, 'Information Systems Manager', 'Korie Dand', '€26196,43');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (56, 2, 'Pharmacist', 'Laurena Carnalan', '€22123,27');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (57, 10, 'Data Coordiator', 'Tracey O''Doohaine', '€33910,09');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (58, 2, 'Community Outreach Specialist', 'Glenine Lesmonde', '€25428,61');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (59, 1, 'VP Quality Control', 'Dorey enzley', '€29962,91');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (60, 7, 'Senior Financial Analyst', 'Jana Eberst', '€24180,18');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (61, 8, 'Media Manager I', 'Carlotta Jobes', '€31898,68');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (62, 1, 'Senior Sales Associate', 'Shawna Zollner', '€30389,17');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (63, 1, 'Human Resources Manager', 'Fred Harrell', '€24229,61');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (64, 10, 'Financial Analyst', 'Davita Welberry', '€30304,41');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (65, 1, 'Recruiting Manager', 'Isidro Thring', '€32424,69');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (66, 7, 'Food Chemist', 'Suzette Banck', '€23999,60');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (67, 7, 'Operator', 'Scott Robilliard', '€29403,84');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (68, 8, 'Clinical Specialist', 'Sapphira Brosetti', '€25590,95');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (69, 5, 'Senior Sales Associate', 'Celisse Cornish', '€25275,66');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (70, 8, 'Paralegal', 'Anstice Bremner', '€30239,10');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (71, 5, 'Web Developer II', 'Byrle Jordan', '€22198,57');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (72, 1, 'Quality Engineer', 'Daryl Edler', '€25256,96');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (73, 6, 'Biostatistician III', 'Falito Lesslie', '€32756,99');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (74, 7, 'Mechanical Systems Engineer', 'Dennet Birrel', '€26236,68');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (75, 9, 'Technical Writer', 'Filmer Windram', '€28535,06');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (76, 2, 'Quality Control Specialist', 'Natka Grier', '€28714,81');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (77, 10, 'Professor', 'Allin Pacht', '€27889,65');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (78, 9, 'Staff Scientist', 'Sloan Bidgod', '€29953,77');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (79, 3, 'Nurse Practicioner', 'Xaviera Rizzardini', '€35774,22');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (80, 4, 'Information Systems Manager', 'Jaime Laffan', '€31938,67');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (81, 7, 'Information Systems Manager', 'Kassi Joska', '€22894,45');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (82, 8, 'VP Sales', 'Alfi Kahane', '€24688,24');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (83, 9, 'Programmer Analyst IV', 'Vinny Sholl', '€27907,60');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (84, 10, 'Technical Writer', 'Arluene Thorald', '€32179,00');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (85, 8, 'Administrative Assistant I', 'Jay Silverthorne', '€35444,41');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (86, 1, 'Project Manager', 'Daron Leyre', '€26194,04');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (87, 4, 'Desktop Support Technician', 'Meredith Davern', '€32652,41');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (88, 2, 'Developer II', 'Abe Harkins', '€27107,72');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (89, 8, 'VP Marketing', 'Hermia Beharrell', '€28791,82');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (90, 4, 'Structural Analysis Engineer', 'Calhoun Krollman', '€28489,53');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (91, 8, 'Sales Representative', 'Cherise Gorsse', '€29494,11');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (92, 6, 'Food Chemist', 'Halsy Riddle', '€29227,23');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (93, 10, 'Budget/Accounting Analyst II', 'Martina Snow', '€32068,95');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (94, 9, 'Community Outreach Specialist', 'Albertine Holbarrow', '€24366,54');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (95, 7, 'Senior Cost Accountant', 'Costa Jersch', '€35519,10');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (96, 10, 'Compensation Analyst', 'Carmine Brimfield', '€35202,72');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (97, 4, 'Senior Sales Associate', 'Feodora Fison', '€27030,87');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (98, 3, 'Actuary', 'Cacilie Cawdery', '€24343,67');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (99, 10, 'Help Desk Operator', 'Kanya Secret', '€34615,52');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (100, 1, 'Physical Therapy Assistant', 'Vachel Scini', '€22614,59');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (101, 8, 'Recruiter', 'Case Joannet', '€24018,41');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (102, 1, 'Chief Design Engineer', 'Eda Filipchikov', '€24338,67');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (103, 1, 'Occupational Therapist', 'Bart Toynbee', '€33556,74');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (104, 5, 'Environmental Tech', 'Tedmund Puddan', '€35377,77');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (105, 9, 'Senior Editor', 'Thatcher Triplett', '€32429,88');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (106, 2, 'Nurse', 'Angus Such', '€25388,34');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (107, 4, 'Recruiter', 'Bruis Slessar', '€22695,91');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (108, 7, 'Structural Analysis Engineer', 'Dominique Gatesman', '€30713,55');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (109, 6, 'Geological Engineer', 'Thane Strognell', '€23176,40');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (110, 7, 'VP Product Management', 'Dani Brazener', '€34949,33');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (111, 7, 'Registered Nurse', 'Oran Rhodes', '€26526,05');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (112, 7, 'Geologist IV', 'Gilli Vigne', '€23039,36');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (113, 6, 'Research Assistant II', 'Benito Allanson', '€25685,90');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (114, 9, 'Payment Adjustment Coordinator', 'Elinor Bromhead', '€34381,41');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (115, 9, 'Environmental Specialist', 'Rory Overlow', '€34096,73');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (116, 6, 'Sales Representative', 'Sheff Lacrouts', '€22367,89');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (117, 10, 'Help Desk Operator', 'Godfree Lammerich', '€35451,71');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (118, 4, 'Software Engineer II', 'Fran Farfolomeev', '€32995,16');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (119, 5, 'Programmer Analyst II', 'Cristiano Wanklyn', '€27183,09');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (120, 5, 'Cost Accountant', 'Jocelyne Hatterslay', '€22511,89');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (121, 2, 'Chemical Engineer', 'Loni Celes', '€25872,01');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (122, 4, 'Financial Advisor', 'Benji Diglin', '€29914,55');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (123, 7, 'Teacher', 'Serena Albrook', '€22574,95');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (124, 8, 'Staff Accountant IV', 'Krystal De Michetti', '€33037,26');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (125, 1, 'Professor', 'Kalila Anger', '€35300,86');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (126, 1, 'Assistant Media Planner', 'Lester Faudrie', '€26998,88');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (127, 10, 'Geologist II', 'Rock Ruggier', '€34740,43');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (128, 10, 'Analog Circuit Design manager', 'Gabriellia Palister', '€34431,53');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (129, 7, 'GIS Technical Architect', 'Howard Grob', '€25630,74');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (130, 1, 'Help Desk Operator', 'Terencio Furmston', '€35925,63');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (131, 4, 'Financial Analyst', 'Blair Groundwator', '€30895,77');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (132, 5, 'Tax Accountant', 'Cordula Fortie', '€22010,27');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (133, 4, 'Analyst Programmer', 'Jonie Herculeson', '€25968,68');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (134, 2, 'Pharmacist', 'Dita Winstone', '€25579,55');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (135, 7, 'Speech Pathologist', 'Chandra Toms', '€25090,71');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (136, 2, 'Desktop Support Technician', 'Reynolds Greiswood', '€34445,27');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (137, 10, 'Structural Engineer', 'Kitti Busher', '€28807,24');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (138, 6, 'General Manager', 'Clevie Bedward', '€24134,15');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (139, 9, 'Administrative Officer', 'Shepard Cutmore', '€25923,98');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (140, 1, 'Environmental Tech', 'Griffie Townrow', '€23353,55');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (141, 8, 'Data Coordiator', 'Sidonia Archambault', '€33609,34');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (142, 3, 'VP Quality Control', 'Mark Yellop', '€28194,82');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (143, 9, 'Quality Engineer', 'Pattie Forrington', '€33136,73');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (144, 5, 'Occupational Therapist', 'Rayna Manvelle', '€33559,50');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (145, 3, 'Media Manager II', 'Roddie Ovitts', '€34876,97');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (146, 3, 'Associate Professor', 'Shepherd Teasey', '€29194,83');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (147, 1, 'Software Engineer IV', 'Forrest Vernay', '€34360,49');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (148, 3, 'Statistician II', 'Bail Janauschek', '€28811,88');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (149, 6, 'Administrative Assistant II', 'Petra Runnett', '€31477,83');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (150, 7, 'Executive Secretary', 'Izaak Penn', '€31016,03');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (151, 1, 'Computer Systems Analyst IV', 'Grier Pinwell', '€22347,51');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (152, 8, 'Health Coach IV', 'Cliff Preddle', '€23853,93');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (153, 10, 'Web Designer II', 'Mar Petri', '€33594,00');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (154, 3, 'Accounting Assistant II', 'Sally Shillum', '€26210,57');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (155, 4, 'Account Representative I', 'Dorie Valencia', '€23976,67');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (156, 5, 'Senior Editor', 'Gonzalo Legerwood', '€28737,87');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (157, 1, 'Senior Sales Associate', 'Briano Arnaud', '€27245,29');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (158, 1, 'Human Resources Assistant I', 'Candi Aronowicz', '€33934,35');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (159, 6, 'Assistant Professor', 'Brittani Roughley', '€23280,54');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (160, 9, 'Teacher', 'Carlo Sollam', '€31119,37');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (161, 5, 'Community Outreach Specialist', 'Chicky Simonutti', '€34282,75');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (162, 10, 'Senior Sales Associate', 'Tremain Klaessen', '€24744,29');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (163, 10, 'Pharmacist', 'Iorgo Glazzard', '€28058,57');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (164, 2, 'Automation Specialist I', 'Greer Phillott', '€35881,19');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (165, 10, 'Civil Engineer', 'Noam Pakenham', '€30043,76');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (166, 9, 'Administrative Assistant IV', 'Bowie Pinnocke', '€26250,46');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (167, 5, 'Dental Hygienist', 'Raina Preist', '€22057,30');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (168, 7, 'Biostatistician IV', 'Marthe Dumbare', '€33277,26');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (169, 9, 'VP Sales', 'Caryl Parmeter', '€33007,47');
insert into Employee (EmployeeNum, DepartmentID, EmployeePosition, EmployeeName, EmployeeSalary) values (170, 10, 'Accountant I', 'Holly Boag', '€32837,01');
