insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (1, 50, 8, 50, '€144,35', 'Bread - White, Sliced');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (2, 37, 8, 35, '€456,92', 'Wine - Red, Cabernet Merlot');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (3, 7, 4, 37, '€129,97', 'Gatorade - Xfactor Berry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (4, 35, 9, 34, '€437,96', 'Soup Campbells Mexicali Tortilla');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (5, 13, 7, 8, '€331,48', 'Soup - French Onion');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (6, 21, 2, 29, '€436,52', 'Lychee');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (7, 33, 1, 50, '€78,64', 'Tomatoes - Hot House');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (8, 49, 3, 2, '€156,46', 'Venison - Denver Leg Boneless');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (9, 26, 8, 27, '€259,56', 'Beef - Tenderloin - Aa');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (10, 8, 6, 26, '€61,06', 'Evaporated Milk - Skim');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (11, 42, 2, 13, '€215,92', 'Cup - 6oz, Foam');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (12, 3, 6, 38, '€424,56', 'Pepper - Chillies, Crushed');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (13, 31, 6, 46, '€158,67', 'Rice Paper');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (14, 9, 10, 24, '€251,87', 'Tomatoes - Cherry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (15, 47, 1, 35, '€142,55', 'Sauce - Soya, Dark');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (16, 15, 8, 41, '€341,67', 'Wine - Red, Metus Rose');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (17, 35, 4, 24, '€450,87', 'Pasta - Lasagna, Dry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (18, 5, 4, 5, '€351,02', 'Radish');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (19, 45, 2, 41, '€119,52', 'Foie Gras');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (20, 19, 3, 39, '€41,28', 'Bread - Pita');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (21, 20, 4, 43, '€375,62', 'Lettuce - Boston Bib');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (22, 41, 2, 37, '€399,84', 'Bread - Pullman, Sliced');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (23, 26, 2, 9, '€241,93', 'Wasabi Powder');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (24, 12, 7, 19, '€211,62', 'Carrots - Jumbo');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (25, 8, 9, 32, '€142,84', 'Glucose');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (26, 27, 6, 46, '€339,75', 'Cheese - Augre Des Champs');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (27, 19, 4, 9, '€78,64', 'Chips - Miss Vickies');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (28, 10, 4, 15, '€125,85', 'Mop Head - Cotton, 24 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (29, 43, 9, 2, '€258,84', 'Carbonated Water - Strawberry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (30, 11, 8, 6, '€395,39', 'Molasses - Fancy');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (31, 23, 1, 46, '€133,95', 'Syrup - Monin, Swiss Choclate');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (32, 48, 8, 3, '€89,04', 'Cod - Fillets');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (33, 23, 2, 2, '€453,01', 'Bagel - Everything');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (34, 43, 10, 44, '€138,40', 'Pepsi - Diet, 355 Ml');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (35, 27, 9, 10, '€64,82', 'Cheese - Cheddar, Old White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (36, 1, 2, 32, '€487,87', 'Sword Pick Asst');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (37, 48, 4, 48, '€12,18', 'Wine - Taylors Reserve');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (38, 4, 8, 47, '€473,62', 'Plate Pie Foil');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (39, 15, 1, 36, '€247,21', 'Bread - Burger');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (40, 48, 9, 48, '€157,38', 'Red Snapper - Fillet, Skin On');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (41, 27, 3, 37, '€146,38', 'Wine - Chianti Classico Riserva');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (42, 21, 5, 25, '€288,88', 'Pasta - Fusili Tri - Coloured');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (43, 20, 8, 21, '€186,64', 'Longos - Assorted Sandwich');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (44, 41, 10, 35, '€217,11', 'Vermouth - Sweet, Cinzano');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (45, 5, 6, 20, '€136,64', 'Foil - 4oz Custard Cup');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (46, 21, 2, 23, '€23,48', 'Sauerkraut');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (47, 36, 7, 31, '€254,58', 'Kiwi');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (48, 36, 9, 4, '€228,24', 'Banana - Green');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (49, 44, 7, 36, '€385,24', 'Calypso - Lemonade');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (50, 10, 7, 32, '€409,09', 'Longos - Chicken Wings');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (51, 9, 9, 35, '€492,40', 'Napkin - Beverage 1 Ply');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (52, 10, 2, 20, '€147,36', 'Nestea - Ice Tea, Diet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (53, 23, 6, 18, '€243,63', 'Galliano');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (54, 21, 3, 46, '€86,09', 'Longos - Chicken Wings');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (55, 45, 10, 44, '€238,77', 'Yeast Dry - Fleischman');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (56, 6, 7, 39, '€64,73', 'Energy Drink - Franks Original');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (57, 2, 10, 7, '€495,58', 'Bread - Pumpernickel');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (58, 31, 5, 29, '€48,79', 'Apple - Northern Spy');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (59, 3, 5, 1, '€34,14', 'Cheese - La Sauvagine');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (60, 30, 6, 8, '€163,33', 'Cheese - Stilton');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (61, 32, 5, 28, '€1,51', 'Savory');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (62, 41, 7, 2, '€161,30', 'Trout - Rainbow, Frozen');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (63, 29, 7, 37, '€289,96', 'Buffalo - Striploin');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (64, 43, 10, 4, '€153,71', 'Trueblue - Blueberry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (65, 37, 4, 34, '€185,95', 'Island Oasis - Raspberry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (66, 22, 9, 2, '€2,86', 'Quiche Assorted');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (67, 3, 4, 50, '€409,96', 'Guinea Fowl');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (68, 9, 5, 6, '€100,19', 'Bulgar');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (69, 19, 1, 20, '€283,17', 'Wine - Two Oceans Sauvignon');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (70, 7, 3, 4, '€454,76', 'Cauliflower');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (71, 49, 3, 39, '€175,12', 'Water - Mineral, Natural');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (72, 10, 6, 32, '€209,09', 'Trueblue - Blueberry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (73, 46, 5, 24, '€142,99', 'Bread - Ciabatta Buns');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (74, 49, 1, 37, '€407,77', 'Bread - Pain Au Liat X12');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (75, 3, 7, 43, '€375,55', 'Yeast Dry - Fermipan');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (76, 46, 3, 1, '€438,12', 'Compound - Mocha');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (77, 10, 8, 31, '€213,51', 'Bread - Raisin Walnut Pull');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (78, 34, 9, 23, '€14,11', 'Wine - Maipo Valle Cabernet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (79, 15, 4, 16, '€461,75', 'Puree - Mocha');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (80, 39, 6, 15, '€343,79', 'Bread - Rosemary Focaccia');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (81, 25, 8, 22, '€46,69', 'Pork - Smoked Back Bacon');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (82, 15, 1, 47, '€468,08', 'Taro Root');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (83, 18, 5, 49, '€90,12', 'Steam Pan - Half Size Deep');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (84, 40, 3, 24, '€248,98', 'Lettuce - Curly Endive');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (85, 33, 2, 18, '€158,11', 'Pail For Lid 1537');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (86, 42, 2, 34, '€265,45', 'Bread Base - Toscano');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (87, 47, 10, 15, '€306,53', 'Yogurt - Plain');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (88, 26, 7, 46, '€48,46', 'Guava');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (89, 37, 10, 26, '€499,05', 'Sauce - Caesar Dressing');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (90, 22, 6, 36, '€351,42', 'Pork - Loin, Boneless');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (91, 21, 9, 7, '€103,23', 'Roe - Flying Fish');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (92, 3, 2, 30, '€222,49', 'Wine - Red, Mouton Cadet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (93, 10, 4, 32, '€441,01', 'Lid - 16 Oz And 32 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (94, 36, 1, 6, '€393,88', 'Sesame Seed');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (95, 14, 6, 23, '€187,27', 'Ecolab - Hobart Washarm End Cap');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (96, 49, 2, 6, '€259,70', 'Beer - Sleemans Honey Brown');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (97, 43, 1, 38, '€55,03', 'Pasta - Cannelloni, Sheets, Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (98, 32, 4, 2, '€81,64', 'Dragon Fruit');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (99, 5, 9, 38, '€303,34', 'Pork - Chop, Frenched');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (100, 33, 1, 47, '€345,79', 'Apricots Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (101, 24, 7, 1, '€317,52', 'Towels - Paper / Kraft');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (102, 39, 1, 3, '€58,33', 'Tequila - Sauza Silver');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (103, 22, 10, 41, '€321,12', 'Star Anise, Whole');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (104, 25, 7, 20, '€287,74', 'Apricots - Dried');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (105, 19, 5, 35, '€66,71', 'Juice - Orange 1.89l');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (106, 13, 3, 39, '€467,85', 'Milk - Buttermilk');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (107, 46, 4, 18, '€190,19', 'Gelatine Powder');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (108, 36, 5, 12, '€424,60', 'Wine - Chablis J Moreau Et Fils');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (109, 32, 10, 40, '€131,56', 'Nut - Walnut, Chopped');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (110, 18, 8, 33, '€444,38', 'Cheese - Taleggio D.o.p.');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (111, 34, 7, 14, '€245,79', 'Yogurt - Raspberry, 175 Gr');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (112, 44, 8, 26, '€280,74', 'Pepper - Chili Powder');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (113, 5, 9, 6, '€59,80', 'Pastry - Apple Large');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (114, 13, 10, 34, '€280,45', 'Flour - Cake');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (115, 29, 4, 12, '€141,52', 'Garbag Bags - Black');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (116, 16, 10, 38, '€96,37', 'Chocolate - Feathers');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (117, 7, 2, 8, '€323,06', 'Shallots');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (118, 26, 3, 37, '€93,11', 'Salt - Sea');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (119, 1, 3, 25, '€139,22', 'Pork - Chop, Frenched');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (120, 19, 5, 2, '€137,44', 'Pepsi - Diet, 355 Ml');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (121, 22, 9, 38, '€421,87', 'Beef - Flank Steak');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (122, 18, 1, 23, '€261,90', 'Jam - Marmalade, Orange');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (123, 39, 10, 39, '€281,14', 'Cheese - Ermite Bleu');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (124, 42, 10, 5, '€394,59', 'Lobster - Tail 6 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (125, 34, 4, 27, '€332,65', 'Table Cloth - 53x69 Colour');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (126, 47, 3, 13, '€26,61', 'Peppercorns - Green');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (127, 37, 5, 18, '€73,83', 'Wine - Winzer Krems Gruner');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (128, 29, 8, 4, '€63,88', 'Muffin - Bran Ind Wrpd');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (129, 20, 4, 40, '€467,38', 'Compound - Mocha');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (130, 23, 10, 1, '€316,91', 'Cognac - Courvaisier');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (131, 46, 3, 28, '€431,95', 'Soup - French Can Pea');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (132, 44, 3, 22, '€488,40', 'Wine - Red, Concha Y Toro');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (133, 46, 5, 33, '€54,11', 'Sauce - Mint');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (134, 30, 3, 37, '€163,14', 'Chocolate - Mi - Amere Semi');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (135, 31, 7, 19, '€246,01', 'Mushroom - Oyster, Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (136, 3, 5, 45, '€377,37', 'Coconut - Whole');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (137, 6, 1, 20, '€315,53', 'Beans - French');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (138, 46, 1, 29, '€254,40', 'Oil - Sesame');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (139, 4, 5, 42, '€311,69', 'Cookie Double Choco');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (140, 49, 2, 50, '€161,69', 'Wine - Rosso Toscano Igt');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (141, 40, 1, 7, '€210,37', 'Sugar - Fine');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (142, 11, 8, 38, '€139,92', 'Macaroons - Homestyle Two Bit');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (143, 12, 9, 3, '€421,07', 'Yeast Dry - Fermipan');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (144, 8, 6, 1, '€68,73', 'Roe - Lump Fish, Black');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (145, 48, 7, 11, '€190,94', 'Pasta - Fettuccine, Dry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (146, 28, 9, 43, '€430,90', 'Trout - Hot Smkd, Dbl Fillet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (147, 34, 8, 32, '€223,61', 'Parsley Italian - Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (148, 19, 2, 20, '€176,29', 'Table Cloth 81x81 White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (149, 34, 2, 48, '€127,63', 'Bread Roll Foccacia');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (150, 39, 1, 26, '€287,14', 'Pastry - Mini French Pastries');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (151, 8, 6, 6, '€243,23', 'Onions - Spanish');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (152, 6, 7, 30, '€324,66', 'Swiss Chard');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (153, 20, 2, 44, '€207,36', 'Country Roll');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (154, 43, 10, 27, '€144,06', 'Potatoes - Yukon Gold 5 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (155, 32, 10, 16, '€499,64', 'Vermacelli - Sprinkles, Assorted');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (156, 36, 9, 32, '€90,53', 'Lid - High Heat, Super Clear');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (157, 37, 2, 12, '€363,90', 'Miso - Soy Bean Paste');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (158, 18, 2, 5, '€112,36', 'Beef - Sushi Flat Iron Steak');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (159, 10, 4, 43, '€275,70', 'Beef - Diced');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (160, 14, 3, 14, '€301,31', 'Pate - Peppercorn');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (161, 2, 1, 49, '€320,99', 'Flour - Corn, Fine');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (162, 13, 10, 43, '€225,52', 'Tea - Herbal - 6 Asst');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (163, 33, 7, 17, '€317,43', 'Cookies Almond Hazelnut');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (164, 10, 3, 38, '€446,58', 'Red Currant Jelly');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (165, 20, 8, 14, '€448,78', 'Appetizer - Mushroom Tart');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (166, 20, 6, 3, '€207,65', 'Cake - Cheese Cake 9 Inch');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (167, 8, 7, 1, '€211,92', 'Tortillas - Flour, 8');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (168, 31, 1, 49, '€351,10', 'Savory');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (169, 14, 7, 48, '€183,39', 'Sherbet - Raspberry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (170, 48, 8, 29, '€404,36', 'Crab - Claws, Snow 16 - 24');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (171, 46, 6, 11, '€24,16', 'Papadam');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (172, 25, 10, 45, '€304,62', 'Muffin Mix - Blueberry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (173, 39, 10, 23, '€443,69', 'Pork - Back Ribs');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (174, 8, 1, 14, '€75,40', 'Cheese - Roquefort Pappillon');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (175, 50, 1, 7, '€414,01', 'Soup - Campbells Asian Noodle');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (176, 36, 6, 31, '€125,48', 'Cheese - St. Andre');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (177, 2, 2, 9, '€487,88', 'Pork - Side Ribs');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (178, 2, 10, 38, '€14,98', 'Cheese - Grana Padano');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (179, 43, 10, 23, '€478,38', 'Water, Tap');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (180, 20, 1, 33, '€359,63', 'Oil - Peanut');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (181, 50, 10, 2, '€395,72', 'Tandoori Curry Paste');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (182, 17, 6, 15, '€486,10', 'Nut - Chestnuts, Whole');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (183, 7, 7, 44, '€378,08', 'Bread - White Epi Baguette');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (184, 22, 3, 16, '€360,67', 'Cheese - Mozzarella, Buffalo');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (185, 21, 2, 48, '€266,24', 'Capers - Ox Eye Daisy');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (186, 33, 6, 15, '€143,89', 'Scallops - 10/20');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (187, 16, 6, 22, '€306,23', 'Flour - All Purpose');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (188, 37, 1, 23, '€79,65', 'Cheese - Comtomme');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (189, 15, 6, 19, '€205,29', 'Goulash Seasoning');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (190, 30, 9, 46, '€438,94', 'Pail With Metal Handle 16l White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (191, 25, 10, 23, '€42,34', 'Tofu - Soft');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (192, 24, 5, 41, '€407,96', 'Wine - White, Riesling, Semi - Dry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (193, 8, 2, 33, '€386,83', 'Sage Ground Wiberg');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (194, 50, 2, 27, '€24,50', 'Pepper - Roasted Red');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (195, 40, 6, 9, '€27,29', 'Cheese - Marble');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (196, 48, 9, 27, '€428,65', 'Soup - Campbells, Creamy');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (197, 27, 4, 14, '€445,12', 'Papadam');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (198, 14, 10, 4, '€227,47', 'Steel Wool');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (199, 8, 5, 44, '€141,39', 'Sprouts - Pea');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (200, 17, 3, 39, '€118,72', 'Bagelers - Cinn / Brown Sugar');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (201, 33, 5, 2, '€74,84', 'Jam - Apricot');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (202, 44, 9, 6, '€354,93', 'Vanilla Beans');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (203, 42, 7, 30, '€15,57', 'Muffin Hinge Container 6');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (204, 32, 2, 48, '€363,95', 'Wine - Cave Springs Dry Riesling');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (205, 2, 7, 17, '€215,85', 'Bread - Kimel Stick Poly');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (206, 6, 9, 13, '€301,02', 'Nut - Hazelnut, Ground, Natural');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (207, 30, 5, 11, '€316,84', 'Flour - All Purpose');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (208, 21, 5, 36, '€210,00', 'Chicken - Wieners');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (209, 14, 3, 12, '€397,15', 'Absolut Citron');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (210, 26, 5, 25, '€387,92', 'Cheese - Brie');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (211, 19, 9, 22, '€227,82', 'Spice - Onion Powder Granulated');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (212, 40, 7, 46, '€78,17', 'Shrimp - Black Tiger 13/15');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (213, 29, 6, 49, '€338,92', 'Vinegar - White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (214, 48, 7, 38, '€378,97', 'Cookies - Amaretto');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (215, 25, 8, 22, '€222,14', 'Soup - Campbells - Chicken Noodle');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (216, 1, 3, 7, '€93,72', 'Sour Puss - Tangerine');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (217, 40, 10, 36, '€22,68', 'Pasta - Orecchiette');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (218, 10, 7, 35, '€20,88', 'V8 - Berry Blend');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (219, 35, 3, 15, '€161,80', 'Sugar - Invert');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (220, 19, 10, 36, '€238,99', 'Bouillion - Fish');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (221, 47, 1, 9, '€123,40', 'Pecan Raisin - Tarts');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (222, 10, 3, 39, '€113,26', 'Tomato - Peeled Italian Canned');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (223, 36, 5, 46, '€44,24', 'Pastry - Trippleberry Muffin - Mini');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (224, 50, 1, 5, '€465,45', 'Oven Mitts 17 Inch');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (225, 36, 2, 21, '€0,54', 'Sprouts Dikon');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (226, 48, 8, 12, '€404,78', 'Wine - Red, Antinori Santa');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (227, 37, 1, 20, '€120,50', 'Cheese - Manchego, Spanish');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (228, 3, 8, 50, '€462,09', 'Coffee Cup 12oz 5342cd');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (229, 46, 7, 27, '€416,11', 'Stainless Steel Cleaner Vision');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (230, 2, 8, 29, '€133,32', 'Appetizer - Mini Egg Roll, Shrimp');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (231, 32, 3, 25, '€275,40', 'Chicken - Breast, 5 - 7 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (232, 26, 6, 41, '€259,78', 'Island Oasis - Peach Daiquiri');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (233, 20, 1, 42, '€496,59', 'Wine - Port Late Bottled Vintage');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (234, 46, 9, 33, '€257,03', 'Ice Cream Bar - Rolo Cone');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (235, 42, 4, 11, '€424,83', 'Sausage - Breakfast');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (236, 40, 6, 31, '€169,30', 'Peppercorns - Pink');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (237, 43, 9, 37, '€429,14', 'Greens Mustard');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (238, 25, 8, 36, '€339,12', 'Garlic - Peeled');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (239, 35, 2, 13, '€381,91', 'Toamtoes 6x7 Select');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (240, 23, 2, 20, '€37,93', 'Pepper - Chillies, Crushed');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (241, 21, 10, 35, '€443,79', 'Cattail Hearts');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (242, 32, 8, 43, '€25,22', 'Tea - Jasmin Green');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (243, 13, 1, 6, '€37,14', 'Oil - Grapeseed Oil');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (244, 2, 1, 39, '€55,82', 'Bok Choy - Baby');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (245, 20, 4, 49, '€212,76', 'Raisin - Golden');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (246, 9, 3, 38, '€143,21', 'Cookie Dough - Double');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (247, 34, 2, 31, '€295,52', 'Crackers - Melba Toast');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (248, 14, 8, 16, '€464,78', 'Pepper - Chilli Seeds Mild');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (249, 11, 1, 49, '€156,68', 'Bread - White Mini Epi');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (250, 4, 3, 34, '€7,69', 'Muffin Hinge Container 6');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (251, 22, 2, 23, '€356,03', 'Bread - Corn Muffaletta');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (252, 47, 7, 27, '€180,94', 'Spinach - Baby');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (253, 35, 8, 1, '€200,49', 'Longos - Lasagna Beef');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (254, 46, 1, 7, '€32,94', 'Mustard - Individual Pkg');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (255, 15, 7, 16, '€172,63', 'Crab - Claws, 26 - 30');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (256, 40, 3, 49, '€184,45', 'Flour - Bran, Red');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (257, 32, 7, 40, '€165,47', 'Muffin Mix - Blueberry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (258, 46, 3, 2, '€281,53', 'Compound - Passion Fruit');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (259, 4, 1, 36, '€332,35', 'Nut - Pine Nuts, Whole');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (260, 16, 10, 31, '€197,61', 'Guava');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (261, 31, 3, 23, '€263,82', 'Table Cloth 53x69 White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (262, 18, 6, 29, '€102,04', 'Coffee - Cafe Moreno');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (263, 36, 10, 18, '€259,80', 'Fennel');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (264, 15, 3, 43, '€216,56', 'Lid - 3oz Med Rec');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (265, 30, 6, 17, '€320,03', 'Bread - Bistro White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (266, 23, 1, 25, '€455,81', 'Flower - Dish Garden');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (267, 20, 4, 12, '€317,14', 'Longos - Assorted Sandwich');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (268, 38, 7, 22, '€174,93', 'Table Cloth 81x81 Colour');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (269, 33, 5, 1, '€231,63', 'Cheese - Romano, Grated');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (270, 10, 1, 38, '€0,86', 'Pepper - Julienne, Frozen');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (271, 18, 10, 24, '€313,81', 'Kahlua');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (272, 40, 5, 6, '€299,91', 'Lamb - Sausage Casings');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (273, 46, 1, 43, '€65,24', 'Red Currant Jelly');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (274, 45, 8, 35, '€87,63', 'Mix - Cocktail Ice Cream');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (275, 25, 4, 44, '€297,09', 'Juice - Prune');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (276, 13, 5, 39, '€344,35', 'Compound - Raspberry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (277, 10, 1, 22, '€336,48', 'Beef - Cooked, Corned');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (278, 38, 4, 44, '€66,51', 'Tuna - Canned, Flaked, Light');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (279, 35, 3, 47, '€231,37', 'Celery Root');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (280, 45, 5, 3, '€401,51', 'Yeast Dry - Fermipan');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (281, 25, 7, 26, '€396,00', 'Beer - Sleemans Honey Brown');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (282, 2, 5, 16, '€156,01', 'Glass - Wine, Plastic, Clear 5 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (283, 13, 1, 49, '€8,64', 'Cheese - Brie');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (284, 29, 9, 5, '€221,88', 'Chocolate - White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (285, 42, 6, 7, '€110,01', 'Vodka - Smirnoff');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (286, 24, 1, 27, '€22,95', 'Chicken - Soup Base');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (287, 8, 10, 48, '€456,02', 'Lemonade - Pineapple Passion');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (288, 27, 8, 16, '€124,69', 'Chicken Breast Wing On');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (289, 14, 1, 37, '€404,02', 'Plums - Red');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (290, 13, 10, 38, '€367,16', 'Pepsi - 600ml');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (291, 45, 6, 27, '€439,56', 'Dehydrated Kelp Kombo');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (292, 13, 1, 43, '€233,77', 'Ice Cream - Fudge Bars');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (293, 14, 5, 8, '€46,36', 'Beef Wellington');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (294, 43, 5, 18, '€436,46', 'Mushrooms - Honey');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (295, 43, 3, 3, '€169,19', 'Wine - Sauvignon Blanc Oyster');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (296, 44, 2, 23, '€445,13', 'Lidsoupcont Rp12dn');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (297, 38, 5, 34, '€335,86', 'Beans - Navy, Dry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (298, 4, 9, 24, '€319,63', 'V8 Pet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (299, 47, 5, 33, '€186,54', 'Brandy Cherry - Mcguinness');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (300, 36, 2, 18, '€56,17', 'Ecolab - Ster Bac');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (301, 10, 8, 10, '€394,63', 'Vector Energy Bar');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (302, 19, 9, 15, '€118,91', 'Lamb - Whole Head Off');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (303, 24, 8, 10, '€476,97', 'Gingerale - Diet - Schweppes');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (304, 28, 10, 17, '€346,14', 'Gherkin');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (305, 28, 3, 9, '€381,25', 'Soup - Campbells Tomato Ravioli');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (306, 27, 5, 29, '€70,68', 'Chocolate - Milk, Callets');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (307, 22, 4, 25, '€250,60', 'Nut - Chestnuts, Whole');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (308, 4, 3, 46, '€161,90', 'Kahlua');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (309, 21, 10, 40, '€449,19', 'Nantucket - Kiwi Berry Cktl.');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (310, 33, 10, 30, '€162,09', 'Mushroom - Chantrelle, Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (311, 12, 4, 11, '€132,22', 'Sauce - Caesar Dressing');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (312, 29, 5, 42, '€300,49', 'Extract - Lemon');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (313, 22, 9, 36, '€412,15', 'Wine - Red, Gamay Noir');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (314, 27, 4, 25, '€60,96', 'Cheese - Gorgonzola');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (315, 24, 10, 44, '€181,89', 'Kellogs Special K Cereal');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (316, 24, 1, 44, '€262,56', 'Squash - Pepper');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (317, 21, 3, 33, '€209,44', 'Vanilla Beans');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (318, 11, 6, 1, '€134,62', 'Wine - Chardonnay Mondavi');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (319, 20, 7, 18, '€495,67', 'Beef Cheek Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (320, 29, 2, 26, '€97,27', 'Sprouts - Peppercress');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (321, 48, 9, 19, '€170,59', 'Salmon - Atlantic, No Skin');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (322, 17, 3, 48, '€260,78', 'Stock - Beef, Brown');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (323, 41, 3, 45, '€282,80', 'Bread - 10 Grain Parisian');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (324, 26, 4, 19, '€428,49', 'Cheese Cheddar Processed');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (325, 24, 9, 8, '€407,02', 'Turkey - Breast, Boneless Sk On');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (326, 16, 3, 39, '€192,71', 'Salmon Atl.whole 8 - 10 Lb');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (327, 4, 3, 33, '€287,79', 'Cheese - Mix');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (328, 24, 10, 21, '€279,79', 'Crackers Cheez It');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (329, 7, 1, 16, '€431,69', 'Rice - Sushi');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (330, 6, 10, 26, '€87,89', 'Tea - Herbal I Love Lemon');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (331, 46, 2, 17, '€450,79', 'Wine - Domaine Boyar Royal');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (332, 36, 4, 9, '€59,58', 'Shrimp - 16/20, Peeled Deviened');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (333, 17, 9, 19, '€409,80', 'Hersey Shakes');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (334, 42, 6, 42, '€215,69', 'Mudslide');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (335, 5, 7, 17, '€348,54', 'Soup - Campbells');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (336, 41, 3, 23, '€404,51', 'Juice - Cranberry, 341 Ml');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (337, 14, 10, 25, '€169,33', 'Cleaner - Comet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (338, 49, 6, 12, '€244,75', 'Squid U5 - Thailand');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (339, 13, 10, 20, '€5,40', 'Napkin - Cocktail,beige 2 - Ply');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (340, 21, 6, 5, '€316,93', 'Southern Comfort');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (341, 35, 1, 9, '€287,09', 'Mussels - Cultivated');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (342, 15, 8, 39, '€30,60', 'Bagel - Ched Chs Presliced');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (343, 3, 3, 24, '€222,24', 'Appetizer - Shrimp Puff');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (344, 1, 3, 25, '€341,25', 'Table Cloth 62x120 White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (345, 45, 9, 35, '€273,29', 'Bread - Crusty Italian Poly');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (346, 2, 8, 37, '€252,19', 'Shrimp - 16/20, Peeled Deviened');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (347, 23, 1, 38, '€188,60', 'Syrup - Monin - Granny Smith');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (348, 45, 1, 42, '€489,48', 'Soup - Verve - Chipotle Chicken');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (349, 1, 5, 46, '€62,58', 'Lettuce - Romaine, Heart');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (350, 50, 4, 23, '€464,16', 'Cookie Dough - Double');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (351, 6, 10, 44, '€112,68', 'Wine - Chateau Aqueria Tavel');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (352, 33, 1, 7, '€34,99', 'Rice - Long Grain');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (353, 9, 2, 40, '€461,22', 'Flower - Commercial Spider');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (354, 8, 4, 1, '€254,20', 'Pork - Caul Fat');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (355, 24, 6, 7, '€189,18', 'Bagelers');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (356, 42, 1, 46, '€110,41', 'Salmon - Sockeye Raw');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (357, 33, 10, 37, '€187,81', 'Gherkin - Sour');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (358, 9, 3, 20, '€188,96', 'Juice - Orange 1.89l');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (359, 13, 9, 23, '€403,24', 'Petite Baguette');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (360, 50, 10, 35, '€54,68', 'Lettuce - Radicchio');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (361, 31, 8, 46, '€31,36', 'Milk - Chocolate 500ml');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (362, 41, 6, 7, '€218,70', 'Pepsi - Diet, 355 Ml');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (363, 34, 7, 41, '€26,88', 'Arrowroot');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (364, 19, 8, 31, '€190,67', 'Sprouts - Brussel');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (365, 29, 4, 9, '€66,55', 'Pepper - Chillies, Crushed');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (366, 36, 10, 16, '€93,89', 'Mustard Prepared');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (367, 24, 9, 21, '€385,29', 'Apple - Northern Spy');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (368, 16, 8, 18, '€362,19', 'Pasta - Gnocchi, Potato');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (369, 28, 2, 41, '€472,26', 'Figs');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (370, 25, 2, 27, '€342,20', 'Bulgar');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (371, 12, 3, 12, '€226,60', 'Sproutsmustard Cress');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (372, 36, 2, 49, '€26,72', 'Tray - 12in Rnd Blk');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (373, 11, 1, 43, '€340,24', 'Phyllo Dough');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (374, 19, 6, 18, '€258,89', 'Sobe - Berry Energy');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (375, 40, 5, 13, '€147,92', 'Wine - Puligny Montrachet A.');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (376, 5, 5, 44, '€464,56', 'Oven Mitts - 15 Inch');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (377, 45, 6, 18, '€239,86', 'Bread - English Muffin');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (378, 42, 8, 48, '€462,87', 'Flour - Chickpea');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (379, 30, 10, 34, '€4,48', 'Wine La Vielle Ferme Cote Du');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (380, 17, 4, 32, '€255,62', 'Sambuca - Ramazzotti');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (381, 9, 2, 46, '€334,95', 'Dragon Fruit');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (382, 39, 6, 16, '€237,94', 'Scallops - Live In Shell');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (383, 25, 8, 29, '€424,94', 'Tart Shells - Sweet, 4');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (384, 29, 2, 3, '€201,38', 'Amaretto');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (385, 20, 4, 25, '€420,78', 'Halibut - Fletches');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (386, 27, 9, 39, '€285,37', 'Tomatoes - Grape');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (387, 23, 10, 27, '€482,81', 'Wine - Muscadet Sur Lie');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (388, 10, 6, 17, '€0,68', 'Chicken Thigh - Bone Out');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (389, 10, 7, 28, '€457,52', 'Pork - Hock And Feet Attached');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (390, 18, 3, 23, '€66,78', 'Oven Mitts - 15 Inch');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (391, 44, 10, 20, '€347,62', 'Shrimp - Black Tiger 6 - 8');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (392, 2, 10, 26, '€372,36', 'Latex Rubber Gloves Size 9');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (393, 7, 6, 10, '€305,75', 'Pail With Metal Handle 16l White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (394, 33, 9, 4, '€5,99', 'Jicama');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (395, 41, 3, 27, '€6,66', 'Ecolab - Power Fusion');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (396, 7, 4, 32, '€78,97', 'Skewers - Bamboo');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (397, 15, 8, 19, '€331,94', 'Cakes Assorted');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (398, 19, 1, 35, '€12,22', 'Cocoa Powder - Natural');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (399, 17, 9, 5, '€497,02', 'Beef Ground Medium');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (400, 32, 9, 6, '€258,67', 'English Muffin');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (401, 12, 3, 8, '€383,78', 'Sauce - Ranch Dressing');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (402, 30, 4, 35, '€434,00', 'Cookies - Fortune');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (403, 36, 6, 44, '€467,34', 'Bread - Frozen Basket Variety');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (404, 18, 3, 13, '€362,07', 'Onions - Green');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (405, 7, 4, 12, '€183,51', 'Beef Ground Medium');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (406, 14, 8, 11, '€221,40', 'Calypso - Lemonade');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (407, 30, 6, 6, '€411,58', 'Cheese - Goat With Herbs');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (408, 32, 2, 31, '€278,07', 'Langers - Ruby Red Grapfruit');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (409, 40, 5, 32, '€16,35', 'Bread - Dark Rye');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (410, 3, 3, 18, '€1,90', 'Energy Drink - Franks Pineapple');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (411, 39, 9, 18, '€359,33', 'Avocado');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (412, 19, 8, 4, '€199,44', 'Tea - Jasmin Green');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (413, 48, 4, 34, '€64,92', 'Bouillion - Fish');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (414, 21, 4, 35, '€384,91', 'Wine - Two Oceans Cabernet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (415, 7, 6, 16, '€159,66', 'Cheese - Ricotta');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (416, 15, 8, 34, '€135,60', 'Wine - Magnotta - Cab Franc');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (417, 20, 8, 20, '€258,09', 'Coconut - Creamed, Pure');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (418, 44, 2, 12, '€297,49', 'Kiwi');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (419, 49, 10, 11, '€253,99', 'Appetizer - Tarragon Chicken');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (420, 32, 3, 23, '€482,66', 'Tomato - Green');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (421, 10, 3, 15, '€385,91', 'Sauce - Hollandaise');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (422, 33, 5, 49, '€197,20', 'French Kiss Vanilla');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (423, 3, 8, 19, '€424,77', 'Lettuce - Mini Greens, Whole');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (424, 3, 7, 3, '€124,17', 'Potatoes - Idaho 100 Count');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (425, 21, 2, 17, '€188,00', 'Tea - Vanilla Chai');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (426, 43, 2, 17, '€312,44', 'Bonito Flakes - Toku Katsuo');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (427, 7, 8, 21, '€232,31', 'Pie Shell - 5');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (428, 46, 7, 49, '€412,40', 'Chicken - Wings, Tip Off');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (429, 50, 5, 15, '€372,32', 'Lamb - Ground');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (430, 11, 7, 31, '€95,90', 'Lemons');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (431, 8, 8, 3, '€82,75', 'Wine - Vovray Sec Domaine Huet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (432, 10, 6, 41, '€207,92', 'Rice Wine - Aji Mirin');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (433, 7, 7, 38, '€48,50', 'Pickle - Dill');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (434, 42, 5, 16, '€340,25', 'Chocolate - Mi - Amere Semi');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (435, 27, 6, 22, '€346,40', 'Chicken - White Meat, No Tender');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (436, 9, 10, 18, '€413,86', 'Beans - Navy, Dry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (437, 38, 2, 32, '€266,16', 'Curry Powder');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (438, 30, 9, 12, '€352,19', 'Appetizer - Assorted Box');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (439, 23, 8, 20, '€135,71', 'Liqueur Banana, Ramazzotti');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (440, 5, 10, 11, '€28,74', 'Radish');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (441, 32, 10, 48, '€235,16', 'Pate - Cognac');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (442, 46, 10, 2, '€62,98', 'Appetizer - Mushroom Tart');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (443, 26, 9, 27, '€3,66', 'Snapple - Iced Tea Peach');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (444, 10, 8, 29, '€312,99', 'Lobster - Tail, 3 - 4 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (445, 33, 2, 23, '€82,65', 'Mushroom - Porcini, Dry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (446, 3, 5, 44, '€190,13', 'Pasta - Fettuccine, Egg, Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (447, 23, 10, 49, '€350,76', 'Lamb - Bones');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (448, 37, 2, 50, '€126,92', 'Quail - Whole, Boneless');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (449, 15, 6, 16, '€464,98', 'Calypso - Black Cherry Lemonade');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (450, 42, 1, 49, '€494,95', 'Rice - Jasmine Sented');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (451, 29, 6, 46, '€406,81', 'Soup - Campbells Bean Medley');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (452, 47, 1, 50, '€50,77', 'Oil - Margarine');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (453, 29, 4, 15, '€449,98', 'Wine - Tribal Sauvignon');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (454, 22, 7, 17, '€193,53', 'Cheese - Havarti, Roasted Garlic');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (455, 39, 1, 16, '€9,91', 'Lid Tray - 12in Dome');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (456, 26, 5, 29, '€403,54', 'Beets - Golden');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (457, 43, 4, 28, '€289,30', 'Pepper - Chili Powder');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (458, 24, 8, 14, '€39,32', 'Red Snapper - Fresh, Whole');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (459, 20, 8, 45, '€235,79', 'Chocolate - Semi Sweet, Calets');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (460, 50, 9, 50, '€200,77', 'Fudge - Chocolate Fudge');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (461, 27, 1, 44, '€115,97', 'Chicken - Breast, 5 - 7 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (462, 31, 10, 4, '€162,84', 'Vinegar - White Wine');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (463, 2, 8, 44, '€478,27', 'Wine - Semi Dry Riesling Vineland');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (464, 40, 7, 34, '€68,04', 'Long Island Ice Tea');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (465, 38, 5, 22, '€499,80', 'Mushrooms - Honey');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (466, 6, 1, 20, '€31,17', 'Mushroom - Enoki, Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (467, 28, 9, 43, '€416,83', 'Island Oasis - Cappucino Mix');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (468, 36, 1, 18, '€131,76', 'Ecolab - Ster Bac');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (469, 6, 8, 33, '€39,73', 'Pasta - Linguini, Dry');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (470, 13, 10, 49, '€210,29', 'Oil - Shortening - All - Purpose');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (471, 4, 8, 28, '€273,83', 'Spinach - Packaged');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (472, 45, 3, 2, '€159,37', 'Capon - Breast, Wing On');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (473, 40, 7, 12, '€359,00', 'Cotton Wet Mop 16 Oz');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (474, 3, 1, 44, '€116,92', 'Stock - Beef, White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (475, 16, 2, 40, '€370,90', 'Piping - Bags Quizna');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (476, 22, 4, 21, '€371,54', 'Muffin Mix - Chocolate Chip');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (477, 3, 4, 33, '€228,12', 'Pasta - Fettuccine, Egg, Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (478, 20, 6, 18, '€168,36', 'Wine - Crozes Hermitage E.');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (479, 12, 3, 27, '€478,58', 'Wine - Shiraz Wolf Blass Premium');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (480, 44, 6, 41, '€174,98', 'Ginsing - Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (481, 13, 7, 3, '€34,62', 'Squid - Tubes / Tenticles 10/20');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (482, 14, 10, 39, '€83,03', 'Ecolab - Solid Fusion');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (483, 32, 1, 11, '€332,49', 'Cheese - Swiss');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (484, 20, 2, 14, '€1,61', 'Cake - Lemon Chiffon');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (485, 43, 9, 1, '€345,60', 'Celery');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (486, 43, 9, 2, '€316,84', 'Turnip - White, Organic');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (487, 13, 6, 40, '€26,34', 'Ostrich - Prime Cut');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (488, 42, 5, 45, '€77,39', 'Chicken - Bones');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (489, 42, 1, 15, '€275,33', 'Flavouring Vanilla Artificial');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (490, 24, 5, 18, '€68,39', 'Lambcasing');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (491, 36, 4, 21, '€270,95', 'Icecream - Dstk Strw Chseck');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (492, 28, 6, 41, '€75,26', 'Lid - 3oz Med Rec');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (493, 11, 3, 6, '€32,16', 'Olives - Black, Pitted');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (494, 36, 3, 37, '€161,41', 'Juice - Grape, White');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (495, 5, 4, 19, '€197,31', 'Ham Black Forest');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (496, 13, 7, 33, '€139,23', 'Basil - Fresh');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (497, 40, 4, 15, '€461,13', 'Pepper - Scotch Bonnet');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (498, 12, 1, 20, '€31,66', 'Capers - Ox Eye Daisy');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (499, 40, 3, 47, '€236,04', 'Pork Loin Cutlets');
insert into Product (ProductID, SupplierID, DepartmentID, ProductStock, ProductCost, ProductName) values (500, 33, 1, 21, '€454,96', 'Foil Cont Round');
