insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (1, '1497 Bonner Center', 'Thoughtsphere', '4986462421', 'shallin0@economist.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (2, '115 Hoard Lane', 'Photobean', '1108022295', 'mrobertis1@bigcartel.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (3, '7170 Village Green Street', 'Nlounge', '4012332338', 'arival2@phpbb.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (4, '91519 Merry Plaza', 'Npath', '7643917153', 'sfavela3@deviantart.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (5, '19151 Glendale Circle', 'Feedfire', '9731799113', 'jdonhardt4@addthis.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (6, '3513 Hollow Ridge Terrace', 'Topicshots', '1314730505', 'dhuntington5@cdc.gov');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (7, '40 Thackeray Court', 'Reallinks', '4285042748', 'afarryan6@sitemeter.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (8, '9468 Larry Road', 'Jabberstorm', '2035748887', 'hunion7@bravesites.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (9, '09 Old Shore Court', 'Vidoo', '7598204161', 'lfeaviour8@t.co');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (10, '432 Old Gate Road', 'Oozz', '7954219422', 'fspinello9@example.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (11, '5842 Morning Place', 'Oyoba', '6632508896', 'mocarrolla@behance.net');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (12, '60067 Boyd Park', 'Meevee', '9894178228', 'awestbergb@opera.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (13, '4425 Eagle Crest Junction', 'Voomm', '3858839142', 'rfraysc@phpbb.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (14, '99213 Karstens Hill', 'Thoughtstorm', '9631182081', 'acowherdd@example.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (15, '8229 Gale Street', 'Talane', '2955322490', 'vohagertye@over-blog.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (16, '9 Melrose Circle', 'Jamia', '4214074795', 'gconeleyf@bbc.co.uk');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (17, '1984 Bultman Alley', 'Oba', '3093618033', 'sbiaggig@usgs.gov');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (18, '37245 Pine View Hill', 'Wordtune', '5629238833', 'kbolithoh@ifeng.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (19, '6 Sauthoff Court', 'Skiba', '4851286022', 'ecummingsi@yolasite.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (20, '4 Main Drive', 'Katz', '5868223532', 'mmcbethj@dyndns.org');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (21, '945 Truax Center', 'Gevee', '9562796053', 'ecartmailk@godaddy.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (22, '9225 Colorado Alley', 'Skyble', '4321883911', 'tfinderl@mail.ru');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (23, '105 Scoville Hill', 'Skidoo', '6644469044', 'wstrattanm@ucla.edu');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (24, '4 Sage Plaza', 'Skipfire', '3414210559', 'cfannonn@ustream.tv');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (25, '8335 Eastwood Junction', 'Livefish', '5645568797', 'kbrendo@umich.edu');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (26, '3 Kingsford Avenue', 'Lazzy', '6622878089', 'cvalentimp@sciencedaily.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (27, '9160 Shopko Junction', 'Dabfeed', '2408843381', 'bbernardelliq@bbb.org');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (28, '03136 Bay Avenue', 'Einti', '3478321980', 'sberndsenr@newyorker.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (29, '0247 Pepper Wood Alley', 'Zooxo', '6449939005', 'qcoleshills@columbia.edu');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (30, '980 Moland Drive', 'Skyndu', '2298266507', 'jcoxent@canalblog.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (31, '792 Superior Park', 'Roomm', '5787408969', 'dgammacku@dion.ne.jp');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (32, '0635 Eastlawn Trail', 'Riffwire', '5952999695', 'keaganv@about.me');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (33, '94946 Blue Bill Park Hill', 'Flashset', '3025567771', 'olabuschagnew@fotki.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (34, '57217 West Way', 'Riffpath', '2167709509', 'sdavisx@newsvine.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (35, '12155 Bultman Terrace', 'Dynabox', '6553096249', 'ffridlingtony@cisco.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (36, '6402 Kim Street', 'Fivechat', '1446834892', 'rcoultz@gov.uk');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (37, '447 Talisman Terrace', 'Zooxo', '3278611499', 'cord10@loc.gov');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (38, '506 Beilfuss Terrace', 'Yodoo', '3026147651', 'cfeacham11@cyberchimps.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (39, '86 Schlimgen Court', 'Meembee', '3787948159', 'ckirkam12@state.gov');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (40, '86378 Nevada Alley', 'Edgewire', '7483159194', 'graittie13@devhub.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (41, '8 Dahle Avenue', 'Kayveo', '1158116862', 'csmullen14@discuz.net');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (42, '57609 Rockefeller Plaza', 'Eabox', '2145715272', 'dcollington15@wikia.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (43, '145 Logan Lane', 'Browsedrive', '1739278109', 'jcardoo16@indiatimes.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (44, '23194 Northwestern Trail', 'Livetube', '2502275052', 'mdzenisenka17@storify.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (45, '282 Stone Corner Lane', 'Chatterpoint', '6609465186', 'fmurrells18@spotify.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (46, '9 Waywood Way', 'Kwinu', '2171563418', 'tdiprose19@europa.eu');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (47, '822 Northland Junction', 'Livetube', '7691611466', 'sbremond1a@t.co');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (48, '762 Old Gate Street', 'Youtags', '8933901486', 'cdiruggero1b@buzzfeed.com');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (49, '854 Dawn Road', 'Gabvine', '8439639576', 'emccourtie1c@wikipedia.org');
insert into Supplier (SupplierID, SupplierAddress, SupplierName, SupplierPhone, SupplierEmail) values (50, '6042 Vidon Drive', 'Yodel', '7563280050', 'wkernes1d@quantcast.com');
